# Generated by Django 4.2.2 on 2023-07-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0002_rename_cancel_date_order_cancelled_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Pay by cash"), ("vnpay", "Pay with VNPAY")],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("in_charge", "In Charge"),
                            ("paid", "Paid"),
                            ("fail", "Fail"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("vnpay_response_code", models.CharField(max_length=2, null=True)),
                ("vnpay_transaction_no", models.CharField(max_length=10, null=True)),
                ("vnpay_secure_hash", models.CharField(max_length=256, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
