# Generated by Django 4.2.2 on 2023-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cancel_date",
            new_name="cancelled_date",
        ),
        migrations.AddField(
            model_name="order",
            name="completed_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("order", "ordered"),
                    ("shipping", "in transit"),
                    ("success", "Order delivered and payment successful"),
                    ("failed", "Order failed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
