# Generated by Django 4.2.4 on 2023-08-15 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_rename_cancel_date_order_cancelled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='shipper',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('order', 'ordered'), ('shipping', 'in transit'), ('success', 'Order delivered and payment successful'), ('failed', 'Order failed'), ('cancelled', 'cancelled'), ('delivery_failed', 'Delivery failed')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.lineitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shipment')),
            ],
            options={
                'db_table': 'delivered_item',
            },
        ),
    ]
