# Generated by Django 4.2.4 on 2023-08-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_shippinginfo_shipper_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivereditem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='order.shipment'),
        ),
    ]
