# Generated by Django 4.2.4 on 2023-08-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_delivereditem_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', ' delivered  successful'), ('failed', 'delivered failed')], default='pending', max_length=15),
        ),
    ]
