# Generated by Django 4.2.4 on 2023-08-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_promotion_order_shipping_fee_shipment_is_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='date_shipped',
        ),
        migrations.AddField(
            model_name='shipment',
            name='failed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipped_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipping', 'shipping'), ('success', ' delivered  successful'), ('failed', 'delivered failed')], default='pending', max_length=15),
        ),
    ]
